---
abstract: 'convert Excel data to text formats'
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: excel2txt
recommends:
  XML::Simple: 0
  YAML: 0
requires:
  Pod::Usage: 0
  Readonly: 0
  Spreadsheet::ParseExcel: 0.2603
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
