---
name: excel2txt
version: 0.04
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
abstract: convert Excel data to text formats
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Pod::Usage: 0
  Readonly: 0
  Spreadsheet::ParseExcel: 0.2603
build_requires:
  Test::More: 0
recommends:
  XML::Simple: 0
  YAML: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
